import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";
import "./globals.css";

import { RolesProvider } from "@/context/RolesContext";
import { fetchRoles } from "@/lib/roles";
import type { Role } from "@/models/roles";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // TODO: Once authentication is implemented, derive user_id from the session
  // token stored in a secure, httpOnly cookie rather than a plain `user_id` cookie.
  const cookieStore = await cookies();
  const rawUserId = cookieStore.get("user_id")?.value;
  const userId = rawUserId ? parseInt(rawUserId, 10) : null;

  const initialRoles: Role[] =
    userId !== null && !isNaN(userId) ? await fetchRoles(userId) : [];

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <RolesProvider initialRoles={initialRoles}>{children}</RolesProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
