name: "🐛 Bug Report"
description: Report something that's broken
title: "fix: <brief description>"
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Bug Description"
      description: What's broken?
      placeholder: "Events page returns 404 when..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: "Steps to Reproduce"
      value: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: What should happen instead?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Error Logs"
      description: Console errors, stack traces, etc.
      render: bash
    validations:
      required: false
